name: Alerts

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Enviar alerta
        run: echo "⚠️ O workflow falhou!"
